[package]
name = "guest"
version = "0.1.0"
authors = ["Karthik Ganeshram <karthik.ganeshram@fermyon.com>"]
edition = "2021"
rust-version = "1.71"

[lib]
crate-type = ["cdylib"]

[dependencies]
spin-sdk = "3.0.0"
spin-cron-sdk = { path = "../sdk" }

[workspace]
